// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {request} from '../models';

export function Greet(arg1:string):Promise<string>;

export function SendStationHttpRequest(arg1:request.StationHttpRequest):Promise<request.StationHttpResponse>;
